### PR TITLE
WIP: Use a default title if none specified

### PR DESCRIPTION
**Pull request by stig**
**This is WIP, and a request for help -- I do not expect it to be merged in its current form.**

I wanted to try to address issue #41, as this would simplify my workflow a lot. (I do a lot of single-commit PRs.) It was relatively easy to get this far, but I've just spent a couple hours fruitlessly reading through magit's docs & source, attempting to figure out how to get the summary from the first commit that is different between the two branches. (Much like github does when you set up a pull request there.) This being my first attempt at contributing to an Elisp package, I would really love some help if possible.

(I suppose an extension of this would be to use magit's `with-editor` -- I'm wondering if one then could get the benefit of `M-p` to simply recall the last commit message? That would sort me out.)

### CODE REVIEW

**Comment by alexander-yakushev** [comment]
@stig Sorry for postponing this, I will merge this PR as soon as the dust settles after the recent rewrites. Thank you!

**Comment by stig** [comment]
Nono! Please don't merge it in its current state :-D it does more harm than good in its current state :-)

**Comment by stig** [comment]
It's just a placeholder at the moment. I've managed to identify the place I want to inject some code, but I don't know what to inject :-D

**Comment by alexander-yakushev** [comment]
As you wish. I will take some time later to think about this and suggest something better. I suppose what you want is #41?

**Comment by stig** [comment]
Exactly that. I just wanted to show that I cared enough to make at least a token effort, but I got stuck trying to figure out how to get the information I wanted from magit.

**Comment by thieman** [comment]
This should be closed following the merge of #71.

**Comment by alexander-yakushev** [comment]
Closing this as resolved. @stig, thanks for your effort! I'm sorry I didn't have time to work this through together with you. And thanks to @thieman for finally implementing this!

**Comment by stig** [comment]
Thanks so much, this will make a big difference to my day-to-day work :-)

**Pull request closed without merging**
