### PR TITLE
Stop making a separate request for every PR

### PR DESCRIPTION
**Pull request by thieman**
I think this is the performance smoking gun I was looking for. It relies on a small change to `gh.el` which I'll link to shortly. Basically, we are currently doing a separate GET for every single PR on `reload` to get stuff like the head and base SHA. All the data we want is actually provided in the list request, we just need to update `gh.el` to stick it on the stub object. Then the status buffer gets *waaaaay* faster. Get excited. :smile:

### CODE REVIEW

**Comment by alexander-yakushev** [comment]
Now these are really good news! Let's hope the `gh.el` is merged and released quickly.

**Comment by thieman** [comment]
Docker has 88 PRs right now. With all my recent improvements active at once, a full reload `# g` takes 4 seconds. :sunglasses:

**Comment by alexander-yakushev** [comment]
This is very nice. Still, I think to comfortably work with that many PRs, we need a separate manager, like magit's branch manager, or something like that.

**Comment by thieman** [comment]
For sure. Baby steps. :baby:

**Comment by piecyk** [comment]
nice :+1:

**Comment by stig** [comment]
+1

**Comment by thieman** [comment]
@alexander-yakushev I think we should be able to get this through now since my gh.el PR got merged and they seem to cut releases regularly. Could you give me some hints on how to update the package requirements to pull a sufficient version?

**Comment by alexander-yakushev** [comment]
Hello Travis, sorry for such a late response. I can see your PR merged into `next` branch in gh.el, but not yet into master. The latest gh.el package in melpa is still without your changes, so unfortunately I can't merge this just yet :(.

**Comment by thieman** [comment]
Alright, I'm trying to grok how that repo is operating and failing. The releases seem to be lagging way behind even what's on `master`, and there's a lot of work in `next` that doesn't end up making it back. Do you understand how he's managing releases? Do we have any other options if we're subject to what seems to be a very slow release cycle?

**Comment by sigma** [comment]
@thieman the `next` branch contains a lot of rewrites, and is basically not ready as a drop-in replacement yet. Feel to reopen your PR against master, there's no reason to wait for that one.

**Comment by alexander-yakushev** [comment]
I assume Yann really struggles finding time for opensource projects right
now. I don't know how he manages development of GH.el, but only master
branch is built into melpa.

**Comment by alexander-yakushev** [comment]
@sigma Sorry, I had started writing on a phone before I saw your response.

**Comment by sigma** [comment]
@alexander-yakushev no worries, I definitely do struggle to find time :) (and that kinda shows)

**Comment by thieman** [comment]
I'll open another PR against master, thanks everyone. :smile:

**Comment by thieman** [comment]
Master PR is here https://github.com/sigma/gh.el/pull/65

**Comment by thieman** [comment]
@alexander-yakushev Master PR got merged and the `gh` I just downloaded from Melpa has the change in it! :smile: What else do we need to merge this, bump the version in the header? Or does Melpa rewrite that to take the latest version of all dependencies?

**Comment by alexander-yakushev** [comment]
@thieman I don't think package.el rewrites it, and I'm not sure we can specify full MELPA date as a dependency. Guess we just merge this and hope people don't do partial updates :).

**Pull request merged**
